{
 "title": "Microservices Observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  { "title": "Visão Geral de Disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status do Serviço",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Threads Ativas na JVM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"$job\"}",
     "legendFormat": "{{job}} - Threads"
    }
   ]
  },
  { "title": "Uso de Recursos JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"$job\"}",
     "legendFormat": "{{job}} - Processo CPU"
    },
    {
     "expr": "system_cpu_usage{job=~\"$job\"}",
     "legendFormat": "{{job}} - Sistema CPU"
    }
   ]
  },
  {
   "title": "Uso de Memória Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=~\"$job\", area=\"heap\"}",
     "legendFormat": "{{job}} - Heap Usado"
    },
    {
     "expr": "jvm_memory_max_bytes{job=~\"$job\", area=\"heap\"}",
     "legendFormat": "{{job}} - Heap Max"
    }
   ]
  },
  { "title": "Métricas HTTP (API)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Throughput HTTP (Requisições por Segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"$job\"}[2m])) by (uri, status, job)",
     "legendFormat": "[{{job}}] {{uri}} ({{status}})"
    }
   ]
  },
  {
   "title": "Latência Média de Requisições HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=~\"$job\"}[2m])) by (uri, job) / sum(rate(http_server_requests_seconds_count{job=~\"$job\"}[2m])) by (uri, job)",
     "legendFormat": "[{{job}}] {{uri}} (latência média)"
    }
   ]
  }
 ]
}